### ISSUE TITLE
Incorrect python docker version

### ISSUE THREAD

**Issue by 0xthedance** [SlingNode/slingnode-ansible-ethereum#151]
I was having the following issue in `TASK [slingnode.ethereum : Start blockchain stack]`:
```
Configuration error - kwargs_from_env() got an unexpected keyword argument 'ssl_version'
```

It seems that docker-py has made a change in v7.0.0 that breaks docker compose written in Python (https://github.com/docker/docker-py/issues/3194).  

Personally, I've solved it by downgrading the docker python module to version 6.1.3, specifying the version manually:
python_modules:
 - docker==6.1.3

**Comment by pgjavier** [comment]
Thank you for reporting this issue. This is related to incompatibilities between docker-py and docker compose v2. Some info in:
- https://github.com/ansible-collections/community.docker/issues/714
- https://github.com/docker/docker-py/issues/3194

We have updated the role to use Ansible docker compose module v2 so with the release 0.32.0 this should be fixed.
